on:
  workflow_dispatch:
  schedule:
  - cron: 0 6 * * 1
  push:
    branches:
    - main
    paths:
    - '.github/workflows/check-release.yml'

name: Release of fontconfig
jobs:
  dependency_releases:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check for new release of fontconfig
      shell: cmd
      run: .ImageMagick\CheckRelease.cmd
